sonar.projectKey=treatttt_interview-helper-system
sonar.organization=treatttt
sonar.sources=lib
sonar.tests=test
sonar.dart.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=lib/dev/**

# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=interview-helper-system
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8